/*
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.imperativeocl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ImperativeOCLCSUiModule extends org.eclipse.qvto.examples.xtext.imperativeocl.ui.AbstractImperativeOCLCSUiModule {
	public ImperativeOCLCSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
