/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.imperativeocl.validation;

import org.eclipse.qvto.examples.xtext.imperativeocl.validation.AbstractImperativeOCLJavaValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ImperativeOCLValidator extends AbstractImperativeOCLJavaValidator {
}
