/*
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.imperativeocl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ImperativeOCLRuntimeModule extends org.eclipse.qvto.examples.xtext.imperativeocl.AbstractImperativeOCLRuntimeModule {

}
