/*
* generated by Xtext
*/
package org.eclipse.qvto.examples.xtext.imperativeocl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ImperativeOCLCSStandaloneSetup extends ImperativeOCLCSStandaloneSetupGenerated{

	public static void doSetup() {
		new ImperativeOCLCSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

