/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.qvtoperational.ui.quickfix;

import org.eclipse.qvto.examples.xtext.imperativeocl.ui.quickfix.ImperativeOCLQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class QVTOperationalQuickfixProvider extends ImperativeOCLQuickfixProvider {
}
