<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eClassifiers xsi:type="ecore:EClass" name="=model: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="model=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="=int: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="int=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="=real: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="real=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="=str: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="str=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="=bool: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="bool=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="bag=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="set=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="oset=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="seq=: false"/>
  <eClassifiers xsi:type="ecore:EClass" name="&lt;>model: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="model&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="&lt;>int: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="int&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="&lt;>real: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="real&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="&lt;>str: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="str&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="&lt;>bool: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="bool&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="bag&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="set&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="oset&lt;>: true"/>
  <eClassifiers xsi:type="ecore:EClass" name="seq&lt;>: true"/>
</ecore:EPackage>
