/*
* generated by Xtext
*/
package org.eclipse.qvto.examples.xtext.imperativeocl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ImperativeOCLCSUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.qvto.examples.xtext.imperativeocl.ui.internal.ImperativeOCLCSActivator.getInstance().getInjector("org.eclipse.qvto.examples.xtext.imperativeocl.ImperativeOCLCS");
	}
	
}
