<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelparam"
    nsURI="http://www.eclipse.org/qvt/1.0.0/Operational/modelparam" nsPrefix="modelparam">
  <eClassifiers xsi:type="ecore:EClass" name="ResourceEObject" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
