package org.eclipse.qvto.examples.xtext.qvtoperational.cs2as.util;

import java.util.List;

import org.eclipse.qvto.examples.pivot.qvtoperational.MappingOperation;
import org.eclipse.qvto.examples.xtext.imperativeocl.cs2as.util.OperationRefFutureResolution;
import org.eclipse.qvto.examples.xtext.qvtoperational.qvtoperationalcs.MappingExtensionCS;
import org.eclipse.qvto.examples.xtext.qvtoperational.qvtoperationalcs.ScopedNameCS;


/**
 * This class should be autogenerated based on mapping description
 * 
 * @author asbh
 *
 */
public class MappingExtensionFutureResolution extends OperationRefFutureResolution<MappingExtensionCS, MappingOperation> {

	public MappingExtensionFutureResolution(MappingExtensionCS csElement) {
		super(csElement, MappingOperation.class);
	}

	public boolean resolve() {		
		// This code should be autogenerated based on mapping description
		MappingExtensionCS csElement = getCS();
		List<ScopedNameCS> test = csElement.getMappingIdentifiers();
		// Use the enviroment to look for the mapping operation to reference
		// invoke XXXAttributtion 
		
		return false;
	}
}