<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtoperationalcs" nsURI="http://www.eclipse.org/qvt/pivot/1.0/QVTOperationalCS"
    nsPrefix="qvtoperationalcs">
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" upperBound="-1"
        eType="#//ImportCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" upperBound="-1" eType="#//UnitElementCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassifierKind">
    <eLiterals name="DATATYPE" literal="datatype"/>
    <eLiterals name="PRIMITIVE" value="1" literal="primitive"/>
    <eLiterals name="EXCEPTION" value="2" literal="exception"/>
    <eLiterals name="CLASS" value="3" literal="class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureKey">
    <eLiterals name="COMPOSES" literal="composes"/>
    <eLiterals name="REFERRENCES" value="1" literal="references"/>
    <eLiterals name="READONLY" value="2" literal="readonly"/>
    <eLiterals name="DERIVED" value="3" literal="derived"/>
    <eLiterals name="STATIC" value="4" literal="static"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InitOp">
    <eLiterals name="EQUALS" literal="="/>
    <eLiterals name="COLON_EQUALS" value="1" literal=":="/>
    <eLiterals name="COLON_COLON_EQUALS" value="2" literal="::="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MetamodelKind">
    <eLiterals name="METAMODEL" literal="metamodel"/>
    <eLiterals name="PACKAGE" value="1" literal="package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParamDirection">
    <eLiterals name="IN" literal="in"/>
    <eLiterals name="INOUT" value="1" literal="inout"/>
    <eLiterals name="OUT" value="2" literal="out"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Qualifier">
    <eLiterals name="BLACKBOX" literal="blackbox"/>
    <eLiterals name="ABSTRACT" value="1" literal="abstract"/>
    <eLiterals name="STATIC" value="2" literal="static"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//UnitCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="segment" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitElementCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompleteSignatureCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleSignatureCS" eSuperTypes="#//CompleteSignatureCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" upperBound="-1"
        eType="#//ParamCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//ParamDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathName" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initPart" eType="#//InitPartCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitPartCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initOp" eType="#//InitOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.essentialocl/model/EssentialOCLCST.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelCS" eSuperTypes="#//UnitElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="#//MetamodelKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathName" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//MetamodelElementCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelElementCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierCS" eSuperTypes="#//MetamodelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intermediate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" unique="false"
        upperBound="-1" eType="#//Qualifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="#//ClassifierKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathName" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//ClassifierFeatureCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierFeatureCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierPropertyCS" eSuperTypes="#//ClassifierFeatureCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureKey" unique="false"
        upperBound="-1" eType="#//FeatureKey"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initPart" eType="#//InitPartCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//MultiplicityCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tilde" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oppositeIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeMultiplicity" eType="#//MultiplicityCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//MultiplicityCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierOperationCS" eSuperTypes="#//ClassifierFeatureCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureKey" unique="false"
        upperBound="-1" eType="#//FeatureKey"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" eType="#//CompleteSignatureCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationCS" eSuperTypes="#//MetamodelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagCS" eSuperTypes="#//MetamodelElementCS #//ClassifierFeatureCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathName" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.essentialocl/model/EssentialOCLCST.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedefCS" eSuperTypes="../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass ../../../../../../../../org.eclipse.ocl.examples.xtext.essentialocl/model/EssentialOCLCST.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
