/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.qvtoperational.ui.contentassist;

import org.eclipse.qvto.examples.xtext.qvtoperational.ui.contentassist.AbstractQVTOperationalProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class QVTOperationalProposalProvider extends AbstractQVTOperationalProposalProvider {
}
