/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.qvtoperational.scoping;

import org.eclipse.qvto.examples.xtext.imperativeocl.scoping.ImperativeOCLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping on how and when
 * to use it
 */
@SuppressWarnings("all")
public class QVTOperationalScopeProvider
		extends ImperativeOCLScopeProvider {
}
