/*
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.imperativeocl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.qvto.examples.xtext.imperativeocl.ui.internal.ImperativeOCLCSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ImperativeOCLCSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ImperativeOCLCSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ImperativeOCLCSActivator.getInstance().getInjector(ImperativeOCLCSActivator.ORG_ECLIPSE_QVTO_EXAMPLES_XTEXT_IMPERATIVEOCL_IMPERATIVEOCLCS);
	}
	
}
