setpref complianceLevel=1.5

# We import a target definition which will be our API Base Line
importtargetdefinition "file://${checkout.location}/org.eclipse.qvto.git/releng/org.eclipse.qvto.releng.buckminster/APIBaseLine.target"
addbaseline -A "Eclipse QVTo API Base Line"

# We set the path of the new target platform
setpref targetPlatformPath="${checkout.location}/buildroot/target.platform"

import --properties "${checkout.location}/buildroot/build.properties" "org.eclipse.qvto.git/releng/org.eclipse.qvto.releng.buckminster/releng/qvto-tests-all.mspec"

build

#junit --launch "org.eclipse.qvto.xtext.qvtcore.tests/.launches/All\ QVTcore\ Tests.launch" --flatXML --output "${checkout.location}/MMT-QVTo.test.results/org.eclipse.qvto.xtext.qvtcore.tests.xml"
#junit --launch "org.eclipse.qvto.xtext.qvtrelation.tests/.launches/All\ QVTrelation\ Tests.launch" --flatXML --output "${checkout.location}/MMT-QVTo.test.results/org.eclipse.qvto.xtext.qvtrelation.tests.xml"

perform --properties "${checkout.location}/buildroot/build.properties" "-Dbuckminster.reference.repository=${reference.repository}" "org.eclipse.qvto.releng.build:eclipse.feature#build"
perform --properties "${checkout.location}/buildroot/build.properties" "org.eclipse.qvto.releng.buckminster:buckminster#setup.promoter"
perform --properties "${checkout.location}/buildroot/build.properties" "org.eclipse.qvto.releng.buckminster:buckminster#setup.publisher"

#perform --properties "${checkout.location}/buildroot/tagging.properties" "org.eclipse.FIXME.build#tag"