/*
* generated by Xtext
*/
package org.eclipse.qvto.examples.xtext.imperativeocl.parser.antlr;

import org.eclipse.qvto.examples.xtext.imperativeocl.services.ImperativeOCLGrammarAccess;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

public class ImperativeOCLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ImperativeOCLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.qvto.examples.xtext.imperativeocl.parser.antlr.internal.InternalImperativeOCLParser createParser(XtextTokenStream stream) {
		return new org.eclipse.qvto.examples.xtext.imperativeocl.parser.antlr.internal.InternalImperativeOCLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GrammmarCS";
	}
	
	public ImperativeOCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ImperativeOCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
