/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.imperativeocl.ui.contentassist;

import org.eclipse.qvto.examples.xtext.imperativeocl.ui.contentassist.AbstractImperativeOCLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ImperativeOCLProposalProvider extends AbstractImperativeOCLProposalProvider {
}
