/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.qvtoperational.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class QVTOperationalDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
