<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ImperativeOCL"
    nsURI="http://www.eclipse.org/qvto/1.0/ImperativeOCL" nsPrefix="eimpocl">
  <eSubpackages name="expressions" nsURI="http://www.eclipse.org/qvto/1.0/ImperativeOCL/Expressions"
      nsPrefix="eimpocl.expr">
    <eClassifiers xsi:type="ecore:EClass" name="AltExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitSwitchAltExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/AltExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/AltExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/AltExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitAssertExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/AssertExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/AssertExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/AssertExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assertion" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="log" eType="#//expressions/LogExp"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" lowerBound="1"
          eType="#//expressions/SeverityKind" defaultValueLiteral="error"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssignExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitAssignExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/AssignExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/AssignExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/AssignExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true">
        <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
          <details key="body" value="defaultOwner"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReset" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitBlockExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/BlockExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/BlockExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/BlockExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputeExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitComputeExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/ComputeExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/ComputeExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/ComputeExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnedElement" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/Variable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictLiteralExp" eSuperTypes="../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/LiteralExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" ordered="false"
          upperBound="-1" eType="#//expressions/DictLiteralPart" containment="true">
        <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
          <details key="body" value="partOwner"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictLiteralPart" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true">
        <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
          <details key="body" value="keyOwner"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true">
        <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
          <details key="body" value="valOwner"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryType" eSuperTypes="../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/CollectionType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier">
        <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
          <details key="body" value="keyDict"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForExp" eSuperTypes="#//expressions/ImperativeLoopExp">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitForExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/ForExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/ForExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/ForExp/accept/U"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeExpression" abstract="true"
        eSuperTypes="../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeIterateExp" eSuperTypes="#//expressions/ImperativeLoopExp">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitImperativeIterateExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/ImperativeIterateExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/ImperativeIterateExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/ImperativeIterateExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/Variable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeLoopExp" eSuperTypes="#//expressions/ImperativeExpression ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/LoopExp">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitImperativeLoopExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/ImperativeLoopExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/ImperativeLoopExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/ImperativeLoopExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstantiationExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitInstantiationExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/InstantiationExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/InstantiationExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/InstantiationExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extent" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedClass" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ListType" eSuperTypes="../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="LogExp" eSuperTypes="../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OperationCallExp">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitLogExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/LogExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/LogExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/LogExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitReturnExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/ReturnExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/ReturnExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/ReturnExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SeverityKind">
      <eLiterals name="error"/>
      <eLiterals name="warning" value="1"/>
      <eLiterals name="fatal" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitSwitchExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/SwitchExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/SwitchExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/SwitchExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alternativePart" upperBound="-1"
          eType="#//expressions/AltExp" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateParameterType" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Typedef" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableInitExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitVariableInitExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/VariableInitExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/VariableInitExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/VariableInitExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/Variable"
          containment="true">
        <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
          <details key="body" value="declaration"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="withResult" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileExp" eSuperTypes="#//expressions/ImperativeExpression">
      <eOperations name="accept">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="if(v instanceof ExtendedVisitor) {&#xD;&#xA;  @SuppressWarnings(&quot;unchecked&quot;)    &#x9;&#x9;&#xD;&#xA;  ExtendedVisitor&lt;T> visitorExt = (ExtendedVisitor) v;    &#x9;&#xD;&#xA;  return visitorExt.visitWhileExp(this);&#xD;&#xA;}&#xD;&#xA;return org.eclipse.m2m.internal.qvt.oml.expressions.util.ForeignVisitorDefaultValue.getDefaultValueForVisitor(v);"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//expressions/WhileExp/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="U">
          <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
            <eTypeArguments eTypeParameter="#//expressions/WhileExp/accept/T"/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
            <eTypeArguments/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//expressions/WhileExp/accept/U"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/OCLExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeOCLVisitor" abstract="true"
        interface="true">
      <eTypeParameters name="T"/>
      <eOperations name="visitAssignExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="assignExp" lowerBound="1" eType="#//expressions/AssignExp"/>
      </eOperations>
      <eOperations name="visitVariableInitExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="variableInitExp" lowerBound="1" eType="#//expressions/VariableInitExp"/>
      </eOperations>
      <eOperations name="visitBlockExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="blockExp" lowerBound="1" eType="#//expressions/BlockExp"/>
      </eOperations>
      <eOperations name="visitComputeExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="computeExp" lowerBound="1" eType="#//expressions/ComputeExp"/>
      </eOperations>
      <eOperations name="visitInstantiationExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="instantiationExp" lowerBound="1" eType="#//expressions/InstantiationExp"/>
      </eOperations>
      <eOperations name="visitWhileExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="whileExp" lowerBound="1" eType="#//expressions/WhileExp"/>
      </eOperations>
      <eOperations name="visitSwitchExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="switchExp" lowerBound="1" eType="#//expressions/SwitchExp"/>
      </eOperations>
      <eOperations name="visitSwitchAltExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="switchAltExp" lowerBound="1" eType="#//expressions/AltExp"/>
      </eOperations>
      <eOperations name="visitLogExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="logExp" lowerBound="1" eType="#//expressions/LogExp"/>
      </eOperations>
      <eOperations name="visitAssertExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="assertExp" lowerBound="1" eType="#//expressions/AssertExp"/>
      </eOperations>
      <eOperations name="visitImperativeLoopExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="imperativeLoopExp" lowerBound="1" eType="#//expressions/ImperativeLoopExp"/>
      </eOperations>
      <eOperations name="visitForExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="forExp" lowerBound="1" eType="#//expressions/ForExp"/>
      </eOperations>
      <eOperations name="visitImperativeIterateExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="imperativeIterateExp" lowerBound="1" eType="#//expressions/ImperativeIterateExp"/>
      </eOperations>
      <eOperations name="visitReturnExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="returnExp" lowerBound="1" eType="#//expressions/ReturnExp"/>
      </eOperations>
      <eOperations name="visitDictLiteralExp">
        <eGenericType eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eParameters name="dictLiteralExp" lowerBound="1" eType="#//expressions/DictLiteralExp"/>
      </eOperations>
      <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//utilities/Visitor">
        <eTypeArguments eTypeParameter="#//expressions/ImperativeOCLVisitor/T"/>
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEnumLiteral"/>
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter"/>
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/CallOperationAction"/>
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/SendSignalAction"/>
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.ocl.ecore/model/OCLEcore.ecore#//ecore/Constraint"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
